
contentRoot: 'content'

tasks:
  full:
    - name: Initialize Modules
      type: createModules

    #- name: Start PouchDB Server # can be avoided by using local files in location
    #  type: execa
    #   args:
    #    action: 'exec'
    #    cmd: yarn
    #    args: ['pouch', '&']
    #    handle: pouchServer


    - name: Initialize downloader
      type: initDownloader
      args:
        directory: 'var/cache'

    - name: Fetching sources
      type: fetchSources
      args:
          forceDownload: false

    - name: Import Content
      type: doContentImport

    - name: Detect Tokens
      type: tokenize


    - name: generate Tiled JSONs
      type: generatedBattleMapTiledJson

    - name: Write content
      type: persistContent
      args:
        overwriteExisting: false

    - name: Create Pouch Db
      type: createPouchDb
      args:
        overwriteExisting: false
        location: 'var/db' #http://127.0.0.1:3010  #Port set in env.pouch -  use 'var/db' for pure file backed intead

    - name: Summary
      type: printSummary

#    - name: Terminate PouchdB # can be avoided by using local files in location
#      type: execa
#      args:
#        action: 'SIGTERM'
#        handle: pouchServer

    #- name: Pouchdb admin # can be avoided by using local files in location
    #  type: open
    #  args:
    #    cmd: http://localhost:3010/_utils//#/_all_dbs


  server:
    - name: Initialize Modules
      type: createModules

    - name: Mount Database
      type: mountDatabase
      args:
        type: 'pouch'
        location: 'var/db'

    - name: Start Webserver
      type: startServer
      args:
        cors:
          origin: '*'
        compress:
          threshold: 2048
        jwt:
          debug: true
          bannedUserIds: []
          revokedTokens: {}

    - name: Open browser
      type: open
      args:
        cmd: http://localhost:3009/assets/monsters/core/aboleth



modules:
  - id: core
    name: Core
    sources:

    - name: System Reference Document (5e)
      type: srdImport

    - name: Monster Manual
      type: xmlImportMonster
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Monster%20Manual%20Bestiary.xml

    - name: Volo's Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Volo's%20Bestiary.xml"

    - name: Player''s Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Player%20Bestiary.xml"

    - name: Phandelver''s Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Phandelver%20Bestiary.xml"

    - name: Omnibus Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Compendiums/Bestiary%20Compendium.xml"

    - name: Tome of Beasts (Homebrew) Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Homebrew%20%26%20Third%20Party/Monsters/Tome%20of%20Beasts.xml"
      flags: ['homebrew']

    - name: Player's Handbook Spells
      type: xmlImportSpell
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Spells/PHB%20Spells.xml

    - name: Elemental Evil Player Companion Spells
      type: xmlImportSpell
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Spells/EE%20Spells.xml

    - name: Sword Coast Adventurer''s Guid Spells
      type: xmlImportSpell
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Spells/SCAG%20Spells.xml

    - name: Unearthed Arcana Starter Spells
      type: xmlImportSpell
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Unearthed%20Arcana/UA%20Starter%20Spells

    - name: Unearthed Arcana Demon Summoning
      type: xmlImportSpell
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Unearthed%20Arcana/Demon%20Summoning.xml

    - name: Omnibus Spells
      type: xmlImportSpell
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Compendiums/Spells%20Compendium.xml

    - name: Magic Items
      type: xmlImportItem
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Items/Magic%20Items.xml

    - name: Mundane Items
      type: xmlImportItem
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Items/Mundane%20Items.xml

    - name: Valuable Items
      type: xmlImportItem
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Items/Valuable%20Items.xml

    - name: Items Omnius
      type: xmlImportItem
      source: https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Compendiums/Items%20Compendium.xml


  - id: ua-alternate
    name: Alternate Settings (UA)
    sources:
    - name: Unearthed Arcana Renaissance
      type: xmlImportItem
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Unearthed%20Arcana/Renaissance%20Items.xml"
    - name: Unearthed Arcana Futuristic Items
      type: xmlImportItem
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Unearthed%20Arcana/Futuristic%20Items.xml"
    - name: Unearthed Arcana Modern Items
      type: xmlImportItem
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Unearthed%20Arcana/Modern%20Items.xml"
    - name: Unearthed Arcana Modern Spells
      type: xmlImportSpell
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Unearthed%20Arcana/Modern%20Spells.xml"


  - id: princes-of-the-apocalypse
    name: Princes of the Apocalypse
    sources:
    - name: Princes of the Apocalypse Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Princes%20of%20the%20Apocalypse%20Bestiary.xml"


  - id: hoard-of-the-dragon-queen
    name: Hoard of the Dragon Queen
    sources:
    - name: Hoard of the Dragon Queen Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Hoard%20of%20the%20Dragon%20Queen%20Bestiary.xml"


  - id: out-of-the-abyss
    name:  Out of the Abyss
    sources:
    - name: Out of the Abyss Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Out%20of%20the%20Abyss.xml"



  - id: the-curse-of-strahd
    name: The Curse Of Strahd
    sources:
    - name: The Curse Of Strahd Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Curse%20of%20Strahd%20Bestiary.xml"

    - name: Curse of Strahd Maps
      type : generatedBattleMapTiledJson
      source: [https://www.worldanvil.com/uploads/maps/4e1ff939e6251a1c703183e0630f8e6a.png]
      encoding: buffer

  - id: storm-kings-thunder
    name: Storm King''s Thunder
    sources:
    - name: Storm King''s Thunder Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Storm%20King's%20Thunder.xml"


  - id: tales-from-the-yawning-portal
    name: Tales from the Yawning Portal
    sources:
    - name: Tales from the Yarwning Portal Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/Tales%20From%20the%20Yawining%20Portal%20Bestiary.xml"



  - id: the-rise-of-tiamat
    name: The Rise Of Tiamat
    sources:
    - name: The Rise Of Tiamat Bestiary
      type: xmlImportMonster
      source: "https://raw.githubusercontent.com/ceryliae/DnDAppFiles/master/Bestiary/The%20Rise%20of%20Tiamat%20Bestiary.xml"

